seed: 42

name: "BarlowTwins_{data_dataset_name}_{backbone_name}_{backbone_use_batch_norm}" 
artifacts_root: "artifacts/pretrain_lightly/barlowtwins"

backbone:
  name: "convnextv2_pico" # "resnet18" / "convnextv2_pico" / "convnextv2_tiny" / "resnext50_32x4d"
  pretrained_weights: null # "imagenet" / null 
  use_batch_norm: False
  kwargs: {}
data:
  dataset_name: "stl10"
  num_workers: 8

trainer:
  max_epochs: 201
  devices: [0]
  accelerator: "gpu"
  # precision: 16
  # sync_batchnorm: True
  accumulate_grad_batches: null # 4
  overfit_batches: 0.0 # 1 / 0.0

optimizer:
  batch_size: 128
  lr: 0.001
  weight_decay: 1e-6

wandb: true # set to false to disable wandb logging

# optimizer:
#   name: "lars"
#   classifier_lr: 0.1
#   weight_decay: 1e-6
#   kwargs:
#     clip_lr: True
#     eta: 0.02
#     exclude_bias_n_norm: True

# method_kwargs:
#   proj_hidden_dim: 4096
#   proj_output_dim: 256
#   pred_hidden_dim: 8192
# momentum:
#   base_tau: 0.99
#   final_tau: 1.0
# scheduler:
#   name: "warmup_cosine"
# checkpoint:
#   enabled: True
#   dir: "artifacts/pretrain"
#   frequency: 1

# disable hydra outputs
hydra:
  output_subdir: null
  run:
    dir: .