seed: 42

name: "Supervised_{data_dataset_name}_{backbone_name}_{backbone_use_batch_norm}" 
artifacts_root: "artifacts/pretrain_lightly/supervised"

backbone:
  name: "convnextv2_pico" # "resnet18" / "convnextv2_pico" / "convnextv2_tiny" / "resnext50_32x4d"
  pretrained_weights: null # "imagenet" / null 
  use_batch_norm: False
  kwargs: {}
data:
  dataset_name: "cifar10"
  num_workers: 8

trainer:
  max_epochs: 201
  devices: [0]
  accelerator: "gpu"
  # precision: 16
  accumulate_grad_batches: null # 4
  overfit_batches: 0.0 # 1 / 0.0

optimizer:
  batch_size: 128
  lr: 0.001
  weight_decay: 1e-6

wandb: true # set to false to disable wandb logging

# disable hydra outputs
hydra:
  output_subdir: null
  run:
    dir: .